name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    env:
      MY_SECRET_KEY: ${{ secrets.AUTH_KEY }} # Define the secret as an environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python my_script.py # Run your Python script
